# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Topes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_inicial', models.FloatField()),
                ('monto_final', models.FloatField()),
                ('operador', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='TipoProcedimiento',
            new_name='Procedimiento',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='objeto',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topes.Procedimiento'),
        ),
    ]
