# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topes', '0002_auto_20170619_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objeto',
            new_name='ObjetoContratacion',
        ),
    ]
